apiVersion: v1
kind: Service
metadata:
  name: colleger-accounts-microservice-service
spec:
  type: ClusterIP
  selector:
    app: colleger-accounts-microservice
  ports:
  - port: 8081
    targetPort: 8081
